### ISSUE TITLE
登録した後スプラッシュ画面へ遷移しない

### ISSUE THREAD

**Issue by jiyuujin** [flutter-osaka-dev/flutter-chat#1]
## Overview
登録した後スプラッシュ画面へ遷移しない
Supabase ユーザーが上手く取得できていなさそう？

※ DB (Supabase) 側の確認は取れている

### Environment
Flutter 3.3.0-stable (iOS 15)

**Comment by dshukertjr** [comment]
これも再現ができないのですが、もしかしたら一時的な不具合だったのかもしれません。
