### ISSUE TITLE
テキスト入力した後チャット画面が更新されない

### ISSUE THREAD

**Issue by jiyuujin** [flutter-osaka-dev/flutter-chat#2]
## Overview
テキスト入力した後チャット画面が更新されない
再描画周りの挙動がおかしそう？

※ DB (Supabase) 側の確認は取れている

### Environment
Flutter 3.3.0-stable (iOS 15)

**Comment by dshukertjr** [comment]
こちら再現ができないのですが、もしかしたらSupabase側の一時的な不具合だったのかもしれません。
